import json
from datetime import datetime, timedelta
from typing import Dict, List
import os
from jinja2 import Template
import base64
from config import settings

class PDFGenerator:
    def __init__(self):
        self.template_dir = os.path.join(os.path.dirname(__file__), "templates")
        os.makedirs(self.template_dir, exist_ok=True)
        self.create_default_template()
    
    def create_default_template(self):
        """Create default HTML template for quotes"""
        template_html = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Quote - {{ quote_data.business_name }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .header { text-align: center; margin-bottom: 30px; }
        .logo { max-width: 200px; max-height: 100px; }
        .quote-info { margin-bottom: 30px; }
        .client-info { margin-bottom: 30px; }
        .items-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
        .items-table th, .items-table td { border: 1px solid #ddd; padding: 12px; text-align: left; }
        .items-table th { background-color: #f2f2f2; }
        .total { text-align: right; font-weight: bold; font-size: 18px; }
        .terms { margin-top: 30px; font-size: 12px; color: #666; }
        .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #999; }
    </style>
</head>
<body>
    <div class="header">
        {% if quote_data.logo_url %}
        <img src="{{ quote_data.logo_url }}" alt="Logo" class="logo">
        {% endif %}
        <h1>{{ quote_data.business_name }}</h1>
        <p>Professional Quote</p>
    </div>
    
    <div class="quote-info">
        <h2>Quote Details</h2>
        <p><strong>Quote #:</strong> {{ quote_data.quote_id }}</p>
        <p><strong>Date:</strong> {{ quote_data.date }}</p>
        <p><strong>Valid Until:</strong> {{ quote_data.valid_until }}</p>
        <p><strong>Job:</strong> {{ quote_data.job_title }}</p>
        <p><strong>Industry:</strong> {{ quote_data.industry }}</p>
        <p><strong>Location:</strong> {{ quote_data.location }}</p>
    </div>
    
    <div class="client-info">
        <h2>Client Information</h2>
        <p><strong>Name:</strong> {{ quote_data.client.name }}</p>
        {% if quote_data.client.company %}
        <p><strong>Company:</strong> {{ quote_data.client.company }}</p>
        {% endif %}
        {% if quote_data.client.email %}
        <p><strong>Email:</strong> {{ quote_data.client.email }}</p>
        {% endif %}
        {% if quote_data.client.phone %}
        <p><strong>Phone:</strong> {{ quote_data.client.phone }}</p>
        {% endif %}
        {% if quote_data.client.address %}
        <p><strong>Address:</strong> {{ quote_data.client.address }}</p>
        {% endif %}
    </div>
    
    <table class="items-table">
        <thead>
            <tr>
                <th>Description</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in quote_data.items %}
            <tr>
                <td>{{ item.description }}</td>
                <td>{{ item.quantity }}</td>
                <td>R{{ "%.2f"|format(item.unit_price) }}</td>
                <td>R{{ "%.2f"|format(item.total) }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    
    <div class="total">
        <p>Total: R{{ "%.2f"|format(quote_data.total) }}</p>
    </div>
    
    {% if quote_data.terms %}
    <div class="terms">
        <h3>Terms & Conditions</h3>
        <p>{{ quote_data.terms }}</p>
    </div>
    {% endif %}
    
    <div class="footer">
        <p>Generated by QuoteRight ZA - AI-Powered Quoting Platform</p>
        <p>Thank you for your business!</p>
    </div>
</body>
</html>
        """
        
        template_path = os.path.join(self.template_dir, "quote_template.html")
        with open(template_path, 'w') as f:
            f.write(template_html)
    
    def generate_quote_html(self, quote_data: Dict, user_data: Dict) -> str:
        """Generate HTML for quote"""
        template_path = os.path.join(self.template_dir, "quote_template.html")
        
        with open(template_path, 'r') as f:
            template_content = f.read()
        
        template = Template(template_content)
        
        # Prepare data for template
        items = quote_data.get('items', [])
        total = sum(item.get('total', 0) for item in items)
        
        template_data = {
            'quote_data': {
                'business_name': user_data.get('business_name', 'Your Business'),
                'logo_url': user_data.get('logo_url'),
                'quote_id': f"Q{quote_data.get('id', '0000')}",
                'date': datetime.now().strftime('%Y-%m-%d'),
                'valid_until': (datetime.now() + timedelta(days=quote_data.get('validity_days', 30))).strftime('%Y-%m-%d'),
                'job_title': quote_data.get('job_title', ''),
                'industry': quote_data.get('industry', ''),
                'location': quote_data.get('location', ''),
                'client': quote_data.get('client_info', {}),
                'items': items,
                'total': total,
                'terms': quote_data.get('terms', '')
            }
        }
        
        return template.render(**template_data)
    
    def save_quote_html(self, quote_data: Dict, user_data: Dict, quote_id: int) -> str:
        """Save quote HTML and return file path"""
        html_content = self.generate_quote_html(quote_data, user_data)
        
        # Create uploads directory
        uploads_dir = os.path.join(os.path.dirname(__file__), "uploads")
        os.makedirs(uploads_dir, exist_ok=True)
        
        # Save HTML file
        filename = f"quote_{quote_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        filepath = os.path.join(uploads_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html_content)
        
        return filepath
    
    def convert_html_to_pdf(self, html_filepath: str) -> str:
        """Convert HTML to PDF (placeholder - would use weasyprint or similar)"""
        # For now, return the HTML filepath
        # In production, you would use weasyprint or puppeteer to convert HTML to PDF
        return html_filepath

# Global PDF generator instance
pdf_generator = PDFGenerator() 