export const SOUTH_AFRICAN_CITIES = [
  'Cape Town',
  'Johannesburg',
  'Durban',
  'Pretoria',
  'Port Elizabeth',
  'Bloemfontein',
  'East London',
  'Pietermaritzburg',
  'Kimberley',
  'Polokwane',
  'Nelspruit',
  'Rustenburg',
  'George',
  'Potchefstroom',
  'Witbank',
  'Vereeniging',
  'Klerksdorp',
  'Welkom',
  'Middelburg',
  'Upington',
  'Paarl',
  'Stellenbosch',
  'Worcester',
  'Oudtshoorn',
  'Hermanus',
  'Mossel Bay',
  'Knysna',
  'Plettenberg Bay',
  'Grahamstown',
  'King Williams Town',
  'Queenstown',
  'Mthatha',
  'Richards Bay',
  'Newcastle',
  'Ladysmith',
  'Empangeni',
  'Vryheid',
  'Dundee',
  'Estcourt',
  'Harrismith',
  'Bethlehem',
  'Kroonstad',
  'Sasolburg',
  'Parys',
  'Vanderbijlpark',
  'Carletonville',
  'Randfontein',
  'Krugersdorp',
  'Roodepoort',
  'Sandton',
  'Randburg',
  'Benoni',
  'Boksburg',
  'Germiston',
  'Springs',
  'Alberton',
  'Edenvale',
  'Kempton Park',
  'Centurion',
  'Bronkhorstspruit',
  'Cullinan',
  'Hammanskraal',
  'Mamelodi',
  'Soshanguve',
  'Atteridgeville',
  'Ga-Rankuwa',
  'Mabopane',
  'Temba',
  'Brits',
  'Hartbeespoort',
  'Madibeng',
  'Moretele',
  'Nokeng tsa Taemane',
  'Thabazimbi',
  'Bela-Bela',
  'Modimolle',
  'Mookgophong',
  'Lephalale',
  'Musina',
  'Louis Trichardt',
  'Thohoyandou',
  'Sibasa',
  'Giyani',
  'Phalaborwa',
  'Hoedspruit',
  'Tzaneen',
  'Letsitele',
  'Modjadjiskloof',
  'Mokopane',
  'Bochum',
  'Lebowakgomo',
  'Jane Furse',
  'Marble Hall',
  'Groblersdal',
  'Lydenburg',
  'Sabie',
  'Barberton',
  'Hazyview',
  'White River',
  'Komatipoort',
  'Malelane',
  'Nkomazi',
  'Ermelo',
  'Standerton',
  'Volksrust',
  'Wakkerstroom',
  'Piet Retief',
  'Secunda',
  'Bethal',
  'Delmas',
  'Balfour',
  'Heidelberg',
  'Nigel',
  'Brakpan',
  'Daveyton',
  'Tembisa',
  'Katlehong',
  'Tokoza',
  'Vosloorus',
  'Thokoza',
  'Duduza',
  'KwaThema',
  'Tsakane',
  'Wattville',
  'Kwa-Guqa',
  'Emalahleni',
  'Kriel',
  'Ogies',
  'Hendrina',
  'Carolina',
  'Badplaas',
  'Amsterdam',
  'Dullstroom',
  'Machadodorp',
  'Waterval Boven',
  'Belfast',
  'Davel',
  'Greylingstad',
  'Leandra',
  'Kinross',
  'Evander',
  'Trichardt',
  'Panbult',
  'Chrissiesmeer',
  'Morgenzon',
  'Amersfoort',
  'Perdekop',
  'Paulpietersburg',
  'Glencoe',
  'Wasbank',
  'Charlestown',
  'Memel',
  'Warden',
  'Villiers',
  'Cornelia',
  'Vrede',
  'Reitz',
  'Lindley',
  'Petrus Steyn',
  'Marquard',
  'Senekal',
  'Paul Roux',
  'Clarens',
  'Fouriesburg',
  'Ficksburg',
  'Clocolan',
  'Ladybrand',
  'Hobhouse',
  'Dewetsdorp',
  'Reddersburg',
  'Edenburg',
  'Jagersfontein',
  'Fauresmith',
  'Koffiefontein',
  'Luckhoff',
  'Jacobsdal',
  'Barkly West',
  'Jan Kempdorp',
  'Hartswater',
  'Pampierstad',
  'Warrenton',
  'Windsorton',
  'Postmasburg',
  'Lime Acres',
  'Danielskuil',
  'Kuruman',
  'Kathu',
  'Hotazel',
  'Olifantshoek',
  'Sishen',
  'Keimoes',
  'Kakamas',
  'Kenhardt',
  'Pofadder',
  'Springbok',
  'Port Nolloth',
  'Alexander Bay',
  'Kleinzee',
  'Steinkopf',
  'Okiep',
  'Nababeep',
  'Concordia',
  'Aggeneys',
  'Pella',
  'Onseepkans',
  'Vioolsdrif',
  'Goodhouse',
  'Rietfontein',
  'Augrabies',
  'Groblershoop',
  'Louisvale',
  'Blouputs',
  'Riemvasmaak',
  'Askham',
  'Andriesvale',
  'Twee Rivieren',
  'Nossob',
  'Mata-Mata',
  'Virginia',
  'Allanridge',
  'Odendaalsrus',
  'Ventersburg',
  'Hennenman',
  'Wesselsbron',
  'Bothaville',
  'Hoopstad',
  'Dealesville',
  'Boshof',
  'Hertzogville',
  'Christiana',
  'Bloemhof',
  'Schweizer-Reneke',
  'Sannieshof',
  'Delareyville',
  'Lichtenburg',
  'Coligny',
  'Koster',
  'Swartruggens',
  'Groot Marico',
  'Zeerust',
  'Ottoshoop',
  'Madikwe',
  'Ganyesa',
  'Setlagole',
  'Mmabatho',
  'Mafikeng',
  'Lomanyaneng',
  'Ramotshere Moiloa',
  'Lokaleng',
  'Morokweng',
  'Vryburg',
  'Stella',
  'Tosca',
  'Amalia',
  'Reivilo',
  'Pokwani',
  'Taung',
  'Pudimoe',
  'Bray',
  'Ganspan',
  'Galeshewe',
  'Ritchie',
  'Modder River',
  'Magersfontein',
  'Riverton',
  'Alexandersfontein',
  'Ulco',
  'Schmidtsdrift',
  'Campbell',
  'Griekwastad',
  'Douglas',
  'Prieska',
  'Marydale',
  'Copperton',
  'Britstown',
  'Hanover',
  'Richmond',
  'Victoria West',
  'Hutchinson',
  'Loxton',
  'Carnarvon',
  'Williston',
  'Calvinia',
  'Nieuwoudtville',
  'Vanrhynsdorp',
  'Klawer',
  'Vredendal',
  'Saldanha',
  'Langebaan',
  'Hopefield',
  'Vredenburg',
  'St Helena Bay',
  'Paternoster',
  'Jacobsbaai',
  'Yzerfontein',
  'Darling',
  'Malmesbury',
  'Moorreesburg',
  'Koringberg',
  'Riebeek-Kasteel',
  'Riebeek West',
  'Porterville',
  'Piketberg',
  'Eendekuil',
  'Aurora',
  'Velddrif',
  'Laaiplek',
  'Dwarskersbos',
  'Britannica Heights',
  'Churchhaven',
  'Tulbagh',
  'Ceres',
  'Prince Alfred Hamlet',
  'Wolseley',
  'Op-die-Berg',
  'Gouda',
  'Wellington',
  'Bain\'s Kloof',
  'Hermon',
  'Franschhoek',
  'Villiersdorp',
  'Grabouw',
  'Elgin',
  'Bot River',
  'Caledon',
  'Genadendal',
  'Greyton',
  'Riviersonderend',
  'Napier',
  'Bredasdorp',
  'Elim',
  'Struisbaai',
  'Arniston',
  'Swellendam',
  'Barrydale',
  'Suurbraak',
  'Bontebok',
  'Witsand',
  'Stilbaai',
  'Jongensfontein',
  'Riversdale',
  'Albertinia',
  'Gouritsmond',
  'Ladismith',
  'Calitzdorp',
  'De Rust',
  'Dysselsdorp',
  'Uniondale',
  'Willowmore',
  'Steytlerville',
  'Klaarstroom',
  'Beaufort West',
  'Merweville',
  'Leeu-Gamka',
  'Fraserburg',
  'Sutherland',
  'Matjiesfontein',
  'Laingsburg',
  'Prince Albert',
  'Murraysburg',
  'Graaff-Reinet',
  'Nieu-Bethesda',
  'Cradock',
  'Tarkastad',
  'Hofmeyr',
  'Steynsburg',
  'Burgersdorp',
  'Venterstad',
  'Noupoort',
  'Colesberg',
  'Norvalspont',
  'Oviston',
  'Gariep Dam',
  'Bethulie',
  'Springfontein',
  'Trompsburg',
  'Philippolis',
  'Smithfield',
  'Rouxville',
  'Zastron',
  'Wepener',
  'Botshabelo',
  'Thaba Nchu',
  'Tweespruit',
  'Excelsior',
  'Winburg',
  'Brandfort',
  'Verkeerdevlei',
  'Bultfontein',
  'Koppies',
  'Heilbron',
  'Frankfort',
  'Tweeling',
  'Oranjeville',
  'Deneysville',
  'Refengkgotso',
  'Zamdela',
  'Sharpeville',
  'Sebokeng',
  'Evaton',
  'Orange Farm',
  'Lenasia',
  'Ennerdale',
  'Eldorado Park',
  'Soweto',
  'Alexandra',
  'Diepsloot',
  'Midrand',
  'Ivory Park',
  'Ebony Park',
  'Clayville',
  'Olifantsfontein',
  'Rabie Ridge',
  'Kaalfontein',
  'Isando',
  'Rhodesfield',
  'Bredell',
  'Norkem Park',
  'Birchleigh',
  'Birchleigh North',
  'Bonaero Park',
  'Chloorkop',
  'Greenstone',
  'Lethabong',
  'Modderfontein',
  'Greenstone Hill',
  'Bedfordview',
  'Primrose',
  'Lambton',
  'Cinderella',
  'Rosebank',
  'Morningside',
  'Rivonia',
  'Sunninghill',
  'Woodmead',
  'Bryanston',
  'Fourways',
  'Dainfern',
  'Lanseria',
  'Honeydew',
  'Ferndale',
  'Blackheath',
  'Linden',
  'Emmarentia',
  'Greenside',
  'Parkhurst',
  'Parktown',
  'Houghton',
  'Killarney',
  'Melville',
  'Auckland Park',
  'Westdene',
  'Sophiatown',
  'Triomf',
  'Westbury',
  'Coronationville',
  'Newlands',
  'Maraisburg',
  'Ruimsig',
  'Mogale City',
  'Kagiso',
  'Munsieville',
  'Azaadville',
  'Westonaria',
  'Khutsong',
  'Fochville',
  'Kokosi',
  'Ikageng',
  'Promosa',
  'Jouberton',
  'Alabama',
  'Kanana',
  'Orkney',
  'Stilfontein',
  'Khuma',
  'Hartbeesfontein',
  'Tigane',
  'Wolmaransstad',
  'Makwassie',
  'Ottosdal',
  'Kosmos',
  'Schoemansville',
  'Ifafi',
  'Letlhabile',
  'Oukasie',
  'Hebron',
  'Jericho',
  'Mmakau',
  'Winterveld',
  'Pienaarsrivier',
  'Rayton',
  'Zithobeni',
  'Ekangala',
  'Rethabiseng',
  'KwaMhlanga',
  'Siyabuswa',
  'Kwaggafontein',
  'Moloto',
  'Dennilton',
  'Roossenekal',
  'Loskop',
  'Stoffberg',
  'Steelpoort',
  'Burgersfort',
  'Ohrigstad',
  'Mashishing',
  'Graskop',
  'Pilgrim\'s Rest',
  'Waterval Onder',
  'Emgwenya',
  'Utrecht',
  'Louwsburg',
  'Pongola',
  'Itala',
  'Nongoma',
  'Ulundi',
  'Babanango',
  'Melmoth',
  'Eshowe',
  'Mtunzini',
  'Gingindlovu',
  'Mandeni',
  'Stanger',
  'KwaDukuza',
  'Ballito',
  'Umhlanga',
  'Verulam',
  'Phoenix',
  'Chatsworth',
  'Pinetown',
  'Kloof',
  'Hillcrest',
  'Gillitts',
  'Westville',
  'Umlazi',
  'Isipingo',
  'Amanzimtoti',
  'Kingsburgh',
  'Scottburgh',
  'Park Rynie',
  'Pennington',
  'Hibberdene',
  'Port Shepstone',
  'Margate',
  'Ramsgate',
  'Southbroom',
  'Port Edward',
  'Kokstad',
  'Mount Currie',
  'Underberg',
  'Himeville',
  'Bulwer',
  'Nottingham Road',
  'Mooi River',
  'Weenen',
  'Colenso',
  'Winterton',
  'Bergville',
  'Kestell',
  'Viljoenskroon',
  'Rooigrond'
];

export const SOUTH_AFRICAN_COUNTRY_CODE = '+27';

export const formatPhoneNumber = (phone: string): string => {
  // Remove any existing country code and formatting
  let cleaned = phone.replace(/[\s\-\(\)]/g, '');
  
  // Remove +27 if it exists
  if (cleaned.startsWith('+27')) {
    cleaned = cleaned.substring(3);
  }
  
  // Remove 27 if it exists at the start
  if (cleaned.startsWith('27')) {
    cleaned = cleaned.substring(2);
  }
  
  // Remove leading 0 if it exists
  if (cleaned.startsWith('0')) {
    cleaned = cleaned.substring(1);
  }
  
  // Add South African country code
  return `+27${cleaned}`;
};

export const displayPhoneNumber = (phone: string): string => {
  // Remove country code for display
  let cleaned = phone.replace(/[\s\-\(\)]/g, '');
  
  if (cleaned.startsWith('+27')) {
    cleaned = '0' + cleaned.substring(3);
  }
  
  return cleaned;
};